#!/bin/bash

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║          DEPLOYMENT STATE AUDIT                                ║"
echo "╚════════════════════════════════════════════════════════════════╝"

echo ""
echo "WHAT I CAN VERIFY FROM GIT:"
echo "─────────────────────────────────────────────────────────────────"

echo ""
echo "1. Latest commits pushed to origin/main:"
git log origin/main --oneline -5

echo ""
echo "2. Commits containing diagnostic endpoint:"
echo "   Commit 7db37ed - Added diagnostic endpoint"
echo "   → Contains: app/api/cron-diagnostic/route.ts"
echo "   → Commit timestamp: $(git log 7db37ed --format=%ai | head -1)"

echo ""
echo "3. Commits with updated vercel.json:"
echo "   Commit 7db37ed - diagnostic cron added"
git show 7db37ed:vercel.json | grep -A1 "cron-diagnostic" && echo "✅ Found diagnostic cron in 7db37ed"

echo ""
echo "   Commit c293ee2 - cleanup (latest)"
git show c293ee2:vercel.json | grep -A1 "cron-diagnostic" && echo "✅ Found diagnostic cron in c293ee2"

echo ""
echo "WHAT I CANNOT VERIFY WITHOUT VERCEL DASHBOARD:"
echo "─────────────────────────────────────────────────────────────────"
echo "❌ Which commit SHA is currently Production deployment"
echo "❌ Whether c293ee2 successfully built"
echo "❌ Whether the build is queued/pending/failed"
echo "❌ Exact deployment timestamp"
echo "❌ Which vercel.json is actually in the active build"

echo ""
echo "WHAT THE DEPLOYED CODE IS TELLING US:"
echo "─────────────────────────────────────────────────────────────────"

echo ""
echo "Test 1: Diagnostic endpoint"
echo "   Command: curl -s https://saintandstory.vercel.app/api/cron-diagnostic"
echo "   Result: HTTP 404"
echo "   Meaning: ❌ Endpoint does not exist in deployed code"

echo ""
echo "Test 2: B2B orchestration endpoint"  
echo "   Command: curl -s https://saintandstory.vercel.app/api/orchestrate/status"
echo "   Result: HTTP 200 (returns ledger data)"
echo "   Meaning: ✅ This endpoint exists in deployed code"

echo ""
echo "Test 3: Vercel Cron Jobs UI"
echo "   Shows: Only /api/orchestrate/b2b-daily"
echo "   Expected if c293ee2 deployed: /api/cron-diagnostic + /api/orchestrate/b2b-daily"
echo "   Meaning: ❌ Diagnostic cron is NOT registered in active deployment"

echo ""
echo "DIAGNOSIS:"
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo "The deployed code does NOT contain the diagnostic endpoint."
echo "This means the active Production deployment is from BEFORE commit 7db37ed."
echo ""
echo "Possible states:"
echo "  A) Active deployment is from commit 3f4a195 (before diagnostic was added)"
echo "  B) Deployment from 7db37ed or c293ee2 failed and Vercel rolled back"
echo "  C) Build is still in progress and hasn't become Production yet"
echo ""
echo "REQUIRED EVIDENCE (from Vercel dashboard):"
echo "─────────────────────────────────────────────────────────────────"
echo "To determine which state is true, I need you to check:"
echo ""
echo "1. Go to: saintandstory.vercel.app → Deployments"
echo "2. Find the most recent Production deployment"
echo "3. Report:"
echo "   • Commit SHA"
echo "   • Status (Ready/Building/Failed)"
echo "   • Timestamp"
echo "   • Whether it shows 'Production' badge"
echo ""
echo "This will immediately answer:"
echo "  - Is c293ee2 deployed? (or 7db37ed? or 3f4a195?)"
echo "  - Is a build in progress?"
echo "  - Did a recent build fail?"

