/**
 * Migration: Create Observations Table (Wave 1.2)
 *
 * Stores individual evidence records for discovered businesses.
 * Each observation is immutable, traceable, and sourced.
 * No interpretation. No themes. No summarization.
 *
 * Traceability chain:
 * Source → Evidence → Observation ID → Future reasoning layers
 *
 * observation_id uses UUID v4 for:
 * - Global uniqueness (no collisions across all instances)
 * - Safe for distributed workers and concurrent execution
 * - Immutable (never changes)
 * - Idempotent (safe for retries)
 */

CREATE TABLE IF NOT EXISTS observations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Identity (globally unique, immutable)
  observation_id UUID NOT NULL UNIQUE,  -- UUID v4, generated by application
  candidate_id UUID NOT NULL REFERENCES discovered_businesses(id) ON DELETE CASCADE,

  -- What was observed (controlled enum, not free text)
  observation_type VARCHAR(50) NOT NULL,  -- BUSINESS_NAME, OPERATIONAL_PHRASE, REVIEW_TEXT, etc.

  -- The raw evidence (no interpretation)
  evidence_text TEXT NOT NULL,  -- Exact text found (or structured value)

  -- Source metadata
  source VARCHAR(20) NOT NULL,  -- 'google_places', 'website', 'review', 'metadata'
  confidence VARCHAR(20) NOT NULL,  -- 'HIGH', 'MEDIUM', 'UNKNOWN' (based on source type only)

  -- Context for traceability
  source_url TEXT,  -- URL where evidence was found
  source_date TIMESTAMPTZ,  -- When source was created (e.g., review date)
  source_author VARCHAR(255),  -- Who created source (e.g., review author)

  -- Timing
  extracted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  cached_until TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '24 hours'),

  -- Audit
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index on candidate_id for batch queries
CREATE INDEX IF NOT EXISTS idx_observations_candidate_id
ON observations(candidate_id);

-- Index on observation_id for direct lookups
CREATE INDEX IF NOT EXISTS idx_observations_id
ON observations(observation_id);

-- Index on observation_type for queries by type
CREATE INDEX IF NOT EXISTS idx_observations_type
ON observations(observation_type);

-- Index on source for source-filtering
CREATE INDEX IF NOT EXISTS idx_observations_source
ON observations(source);

-- Index on extracted_at for cache invalidation
CREATE INDEX IF NOT EXISTS idx_observations_extracted_at
ON observations(extracted_at DESC);

-- Composite index for common queries: all observations for a candidate
CREATE INDEX IF NOT EXISTS idx_observations_candidate_type
ON observations(candidate_id, observation_type);
