"use client";

import { useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import Link from "next/link";
import { JourneyProgress } from "../components/journey-progress";

interface EmailDraft {
  subject: string;
  body: string;
  pressureType: "recognition" | "transformation" | "logical";
  variant: "A" | "B";
  confidenceScore?: number;
}

interface ProspectOutreach {
  id: string;
  businessName: string;
  contactName?: string;
  contactEmail?: string;
  recentEngagement?: string;
}

interface OutreachState {
  loading: boolean;
  error: string | null;
  prospect: ProspectOutreach | null;
  emailDraft: EmailDraft | null;
  sending: boolean;
  sendError: string | null;
  sentConfirm: boolean;
}

export default function OutreachPage() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const prospectId = searchParams.get("prospectId");

  const [state, setState] = useState<OutreachState>({
    loading: true,
    error: null,
    prospect: null,
    emailDraft: null,
    sending: false,
    sendError: null,
    sentConfirm: false,
  });

  const [form, setForm] = useState<EmailDraft>({
    subject: "",
    body: "",
    pressureType: "recognition",
    variant: "A",
  });

  // Fetch prospect and email draft
  useEffect(() => {
    const fetchOutreachData = async () => {
      if (!prospectId) {
        setState((s) => ({
          ...s,
          loading: false,
          error: "No prospect selected. Please qualify from Understand.",
        }));
        return;
      }

      try {
        setState((s) => ({ ...s, loading: true, error: null }));

        // Fetch prospect details
        const prospectRes = await fetch(`/api/b2b/prospect/${prospectId}`);
        if (!prospectRes.ok)
          throw new Error("Failed to load prospect details");

        const prospect = await prospectRes.json();

        // Fetch email draft (generated by system)
        const emailRes = await fetch(`/api/b2b/outreach/${prospectId}`);
        let emailDraft = null;
        if (emailRes.ok) {
          emailDraft = await emailRes.json();
        }

        setState((s) => ({
          ...s,
          loading: false,
          prospect,
          emailDraft,
        }));

        // Pre-fill form if draft exists
        if (emailDraft) {
          setForm({
            subject: emailDraft.subject || "",
            body: emailDraft.body || "",
            pressureType: emailDraft.pressureType || "recognition",
            variant: emailDraft.variant || "A",
            confidenceScore: emailDraft.confidenceScore,
          });
        }
      } catch (error) {
        const message =
          error instanceof Error ? error.message : "Failed to load outreach data";
        setState((s) => ({
          ...s,
          loading: false,
          error: message,
        }));
      }
    };

    fetchOutreachData();
  }, [prospectId]);

  // Handle send email
  const handleSendEmail = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!prospectId || !state.prospect?.contactEmail) {
      setState((s) => ({
        ...s,
        sendError: "Missing contact email. Please go back and qualify.",
      }));
      return;
    }

    try {
      setState((s) => ({ ...s, sending: true, sendError: null }));

      const res = await fetch("/api/b2b/send-email", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          prospectId,
          email: state.prospect.contactEmail,
          subject: form.subject,
          body: form.body,
          pressureType: form.pressureType,
          variant: form.variant,
        }),
      });

      if (!res.ok) throw new Error(`HTTP ${res.status}: Send failed`);

      // Success - show confirmation
      setState((s) => ({
        ...s,
        sending: false,
        sentConfirm: true,
      }));

      // Redirect to Pipeline after 2 seconds
      setTimeout(() => {
        router.push("/operator/pipeline");
      }, 2000);
    } catch (error) {
      const message =
        error instanceof Error ? error.message : "Failed to send email";
      setState((s) => ({
        ...s,
        sending: false,
        sendError: message,
      }));
    }
  };

  // Loading state
  if (state.loading) {
    return (
      <div className="px-4 md:px-12 py-10 max-w-4xl">
        <div className="flex justify-center py-12">
          <div className="text-center">
            <div className="w-8 h-8 border-2 border-[#E8E8E8] border-t-[#0D0D0D] rounded-full animate-spin mx-auto mb-4"></div>
            <p className="text-sm text-[#666666]">Preparing outreach draft...</p>
          </div>
        </div>
      </div>
    );
  }

  // Error state
  if (state.error || !state.prospect) {
    return (
      <div className="px-4 md:px-12 py-10 max-w-4xl">
        <JourneyProgress currentStage="outreach" />

        <div className="mb-12">
          <h1 className="font-sans font-black text-[#0D0D0D] text-4xl md:text-5xl tracking-tight leading-tight mb-3">
            Outreach
          </h1>
        </div>

        <div className="border border-[#E8E8E8] rounded-lg p-8 bg-white text-center">
          <p className="text-sm text-[#666666] mb-4">
            {state.error || "No prospect selected. Please qualify from Understand."}
          </p>
          <Link
            href="/operator/discover"
            className="text-xs font-semibold text-[#0D0D0D] hover:text-[#666666] transition-colors"
          >
            Go back to Discover
          </Link>
        </div>
      </div>
    );
  }

  // Success confirmation
  if (state.sentConfirm) {
    return (
      <div className="px-4 md:px-12 py-10 max-w-4xl">
        <div className="border border-[#E8E8E8] rounded-lg p-12 bg-[#F5F5F5] text-center">
          <div className="mb-4 text-3xl">✓</div>
          <h2 className="text-2xl font-black text-[#0D0D0D] mb-2">
            Email sent!
          </h2>
          <p className="text-sm text-[#888888] mb-6">
            Moving {state.prospect.businessName} to Pipeline.
          </p>
          <Link
            href="/operator/pipeline"
            className="text-xs font-semibold text-[#0D0D0D] hover:text-[#666666] transition-colors"
          >
            View Pipeline →
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="px-4 md:px-12 py-10 max-w-4xl">
      {/* Journey Progress */}
      <JourneyProgress currentStage="outreach" prospectId={state.prospect?.id} />

      {/* Header */}
      <div className="mb-12">
        <h1 className="font-sans font-black text-[#0D0D0D] text-4xl md:text-5xl tracking-tight leading-tight mb-3">
          Outreach
        </h1>
        <p className="text-sm md:text-base text-[#888888] font-normal">
          Compose and send email to {state.prospect.businessName}.
        </p>
      </div>

      {/* Divider */}
      <div className="h-px bg-[#E8E8E8] mb-12"></div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-12">
        {/* Left Column: Prospect Summary */}
        <div>
          <section className="mb-12">
            <h2 className="text-sm font-semibold text-[#0D0D0D] uppercase tracking-[0.15em] mb-6">
              Prospect
            </h2>
            <div className="space-y-3">
              <div>
                <p className="text-xs text-[#888888] uppercase tracking-[0.1em] mb-1">
                  Company
                </p>
                <p className="text-base font-semibold text-[#0D0D0D]">
                  {state.prospect.businessName}
                </p>
              </div>

              {state.prospect.contactName && (
                <div>
                  <p className="text-xs text-[#888888] uppercase tracking-[0.1em] mb-1">
                    Contact
                  </p>
                  <p className="text-sm text-[#0D0D0D]">
                    {state.prospect.contactName}
                  </p>
                </div>
              )}

              {state.prospect.contactEmail && (
                <div>
                  <p className="text-xs text-[#888888] uppercase tracking-[0.1em] mb-1">
                    Email
                  </p>
                  <p className="text-sm text-[#0D0D0D]">
                    {state.prospect.contactEmail}
                  </p>
                </div>
              )}

              {state.prospect.recentEngagement && (
                <div className="pt-4 border-t border-[#E8E8E8]">
                  <p className="text-xs text-[#888888] uppercase tracking-[0.1em] mb-2">
                    Recent Signal
                  </p>
                  <p className="text-sm text-[#0D0D0D]">
                    {state.prospect.recentEngagement}
                  </p>
                </div>
              )}
            </div>
          </section>

          {/* Divider */}
          <div className="h-px bg-[#E8E8E8] mb-12"></div>

          {/* Pressure Type Reference */}
          <section>
            <h2 className="text-sm font-semibold text-[#0D0D0D] uppercase tracking-[0.15em] mb-6">
              Email Approaches
            </h2>
            <div className="space-y-4">
              <div>
                <p className="text-xs font-semibold text-[#0D0D0D] mb-1">
                  Recognition
                </p>
                <p className="text-xs text-[#888888]">
                  Highlight their success & achievements
                </p>
              </div>
              <div>
                <p className="text-xs font-semibold text-[#0D0D0D] mb-1">
                  Transformation
                </p>
                <p className="text-xs text-[#888888]">
                  Show what's possible with your service
                </p>
              </div>
              <div>
                <p className="text-xs font-semibold text-[#0D0D0D] mb-1">
                  Logical
                </p>
                <p className="text-xs text-[#888888]">
                  Facts, data, and business case
                </p>
              </div>
            </div>
          </section>
        </div>

        {/* Right Column: Email Composer */}
        <div>
          <div className="border border-[#E8E8E8] rounded-lg p-8 bg-white">
            <h2 className="text-sm font-semibold text-[#0D0D0D] uppercase tracking-[0.15em] mb-8">
              Email
            </h2>

            <form onSubmit={handleSendEmail} className="space-y-6">
              {/* Pressure Type */}
              <div>
                <label className="text-xs font-semibold text-[#0D0D0D] uppercase tracking-[0.1em] block mb-3">
                  Approach
                </label>
                <select
                  value={form.pressureType}
                  onChange={(e) =>
                    setForm((f) => ({
                      ...f,
                      pressureType: e.target.value as EmailDraft["pressureType"],
                    }))
                  }
                  className="w-full px-3 py-2 bg-[#F9F9F9] border border-[#E8E8E8] text-sm text-[#0D0D0D] focus:outline-none focus:border-[#0D0D0D] transition-colors rounded"
                >
                  <option value="recognition">Recognition</option>
                  <option value="transformation">Transformation</option>
                  <option value="logical">Logical</option>
                </select>
              </div>

              {/* Variant */}
              <div>
                <label className="text-xs font-semibold text-[#0D0D0D] uppercase tracking-[0.1em] block mb-3">
                  A/B Variant
                </label>
                <div className="flex gap-3">
                  {["A", "B"].map((variant) => (
                    <button
                      key={variant}
                      type="button"
                      onClick={() =>
                        setForm((f) => ({
                          ...f,
                          variant: variant as EmailDraft["variant"],
                        }))
                      }
                      className={`flex-1 px-3 py-2 rounded text-sm font-semibold transition-colors ${
                        form.variant === variant
                          ? "bg-[#0D0D0D] text-white"
                          : "bg-[#F5F5F5] text-[#0D0D0D] hover:bg-[#E8E8E8]"
                      }`}
                    >
                      Variant {variant}
                    </button>
                  ))}
                </div>
              </div>

              {/* Subject */}
              <div>
                <label className="text-xs font-semibold text-[#0D0D0D] uppercase tracking-[0.1em] block mb-2">
                  Subject
                </label>
                <input
                  type="text"
                  value={form.subject}
                  onChange={(e) =>
                    setForm((f) => ({ ...f, subject: e.target.value }))
                  }
                  placeholder="Email subject line..."
                  className="w-full px-4 py-2 bg-[#F9F9F9] border border-[#E8E8E8] text-sm text-[#0D0D0D] placeholder-[#C9C9C9] focus:outline-none focus:border-[#0D0D0D] transition-colors rounded"
                />
                <p className="text-xs text-[#888888] mt-1">
                  {form.subject.length}/60 characters
                </p>
              </div>

              {/* Body */}
              <div>
                <label className="text-xs font-semibold text-[#0D0D0D] uppercase tracking-[0.1em] block mb-2">
                  Message
                </label>
                <textarea
                  value={form.body}
                  onChange={(e) =>
                    setForm((f) => ({ ...f, body: e.target.value }))
                  }
                  placeholder="Edit the email message..."
                  rows={8}
                  className="w-full px-4 py-3 bg-[#F9F9F9] border border-[#E8E8E8] text-sm text-[#0D0D0D] placeholder-[#C9C9C9] focus:outline-none focus:border-[#0D0D0D] transition-colors rounded"
                />
                <p className="text-xs text-[#888888] mt-1">
                  {form.body.length}/500 characters
                </p>
              </div>

              {/* Error */}
              {state.sendError && (
                <div className="p-3 bg-[#FFF5F5] border border-[#FFE0E0] rounded">
                  <p className="text-xs text-[#DC2626]">{state.sendError}</p>
                </div>
              )}

              {/* Buttons */}
              <div className="flex gap-3 pt-6 border-t border-[#E8E8E8]">
                <button
                  type="submit"
                  disabled={state.sending || !form.subject || !form.body}
                  className="flex-1 px-4 py-3 bg-[#0D0D0D] text-white text-xs font-semibold rounded hover:bg-[#333333] transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  {state.sending ? "Sending..." : "Send Email"}
                </button>
                <Link
                  href="/operator/discover"
                  className="px-4 py-3 border border-[#E8E8E8] text-[#0D0D0D] text-xs font-semibold rounded hover:border-[#0D0D0D] transition-colors"
                >
                  Skip
                </Link>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  );
}
