import type { CityPageData } from "@/components/CityLandingPage";

const STEPS = [
  { num: "01", title: "Tell us what's moving.", desc: "Fill in the basics. 60 seconds. No account needed." },
  { num: "02", title: "We find your driver", desc: "Verified local driver, matched and confirmed by our team." },
  { num: "03", title: "Confirm your price", desc: "Fixed on the call before anything moves." },
  { num: "04", title: "Move day", desc: "On time. Professional. Done properly." },
];

export const PROGRAMMATIC_CITIES: (CityPageData & { slug: string })[] = [
  {
    slug: "nottingham-removals",
    city: "Nottingham",
    headline: "N<span class=\"font-display italic font-normal\">o</span>ttingh<span class=\"font-display italic font-normal\">a</span>m rem<span class=\"font-display italic font-normal\">o</span>v<span class=\"font-display italic font-normal\">a</span>ls.<br />Fixed price.",
    sub: "Tell us about your Nottingham removal. Verified driver matched and confirmed by our team.",
    stats: [
      { stat: "4.9★", label: "Verified reviews" },
      { stat: "< 15m", label: "Response time" },
      { stat: "Fixed", label: "Price. Always." },
      { stat: "NG1–NG25", label: "All postcodes" },
    ],
    steps: STEPS,
    testimonials: [
      { initials: "LB", name: "Laura B.", location: "Lace Market → West Bridgford", quote: "Posted the job at 9am. Called back before I'd put the kettle on. Fixed price, driver on time. Exactly what was promised." },
      { initials: "AM", name: "Adam M.", location: "Beeston → Arnold", quote: "Student flat to shared house. Fixed price, no van hire, no stress. These guys made it simple." },
      { initials: "CO", name: "Claire O.", location: "Mapperley → Clifton", quote: "3-bed move. Two vans, team of three. Everything placed in the right room. Wouldn't use anyone else." },
    ],
    faq: [
      { q: "Do you cover all Nottingham postcodes?", a: "We cover all NG postcodes including West Bridgford, Arnold, Beeston, and surrounding areas. Seven days a week, 7am to 10pm." },
      { q: "Is the price fixed?", a: "Completely fixed. Confirmed on the call before anything moves. Nothing added on move day without your approval." },
      { q: "Can I book same-day in Nottingham?", a: "Same-day is available most days. Post before 10am for the best slots." },
      { q: "Are your drivers vetted?", a: "Every driver is background-checked, insured, and rated by real customers before being assigned any job." },
      { q: "How quickly do you respond?", a: "We call within 15 minutes of posting. Driver matched and price locked before we hang up." },
    ],
    source: "nottingham_removals",
  },
  {
    slug: "coventry-removals",
    city: "Coventry",
    headline: "C<span class=\"font-display italic font-normal\">o</span>ventry rem<span class=\"font-display italic font-normal\">o</span>v<span class=\"font-display italic font-normal\">a</span>ls.<br />N<span class=\"font-display italic font-normal\">o</span> surprises.",
    sub: "Tell us about your Coventry removal. Fixed price confirmed on the call. Verified driver every time.",
    stats: [
      { stat: "4.9★", label: "Verified reviews" },
      { stat: "< 15m", label: "Response time" },
      { stat: "Fixed", label: "Price. Always." },
      { stat: "CV1–CV8", label: "All postcodes" },
    ],
    steps: STEPS,
    testimonials: [
      { initials: "TK", name: "Tom K.", location: "City Centre → Earlsdon", quote: "Fixed price quoted on the call. Fixed price paid at the end. No additions, no arguments. Exceptional." },
      { initials: "RJ", name: "Rachel J.", location: "Canley → Binley", quote: "Same-day move sorted in hours. Driver was professional, careful, and arrived exactly on time." },
      { initials: "MO", name: "Mike O.", location: "Styvechale → Tile Hill", quote: "4-bed house, student stuff included. Everything handled perfectly. Worth every penny." },
    ],
    faq: [
      { q: "Do you cover all Coventry postcodes?", a: "We cover all CV postcodes. Seven days a week, 7am to 10pm." },
      { q: "Is the price fixed?", a: "Completely fixed. The number confirmed on the call is the number you pay." },
      { q: "How fast is the response?", a: "We call within 15 minutes of posting. Driver matched and price locked before we hang up." },
      { q: "Can I book same-day in Coventry?", a: "Same-day is available most days. Post before 10am." },
      { q: "Are drivers background-checked?", a: "Every driver is verified, insured, and rated by real customers before assignment." },
    ],
    source: "coventry_removals",
  },
  {
    slug: "leicester-removals",
    city: "Leicester",
    headline: "Le<span class=\"font-display italic font-normal\">i</span>cester rem<span class=\"font-display italic font-normal\">o</span>v<span class=\"font-display italic font-normal\">a</span>ls.<br />D<span class=\"font-display italic font-normal\">o</span>ne pr<span class=\"font-display italic font-normal\">o</span>perly.",
    sub: "Tell us about your Leicester removal. Verified driver. Fixed price. No guesswork.",
    stats: [
      { stat: "4.9★", label: "Verified reviews" },
      { stat: "< 15m", label: "Response time" },
      { stat: "Fixed", label: "Price. Always." },
      { stat: "LE1–LE19", label: "All postcodes" },
    ],
    steps: STEPS,
    testimonials: [
      { initials: "PD", name: "Priya D.", location: "Narborough Road → Oadby", quote: "Called within a minute. Fixed price locked on the spot. Driver arrived early and worked like a professional. Top class." },
      { initials: "JW", name: "Jamie W.", location: "Braunstone → Wigston", quote: "3-bed house cleared in an afternoon. Two vans, team of three. Everything where it needed to be." },
      { initials: "SL", name: "Selina L.", location: "City Centre → Birstall", quote: "Student move from halls. Fixed price, no van hire stress. Done in three hours. Brilliant service." },
    ],
    faq: [
      { q: "Do you cover all Leicester postcodes?", a: "We cover all LE postcodes including Oadby, Wigston, Birstall, and surrounding areas. Seven days a week, 7am to 10pm." },
      { q: "Is the price fixed?", a: "Completely fixed. Confirmed before anything moves. Nothing added on the day." },
      { q: "Can you do student moves in Leicester?", a: "De Montfort and Leicester University students, end of term, halls to flat. Fixed price, no van hire." },
      { q: "How quickly do you respond?", a: "Within 15 minutes of posting. Driver and price confirmed before we hang up." },
      { q: "Are drivers verified?", a: "Every driver is background-checked, insured, and rated by real customers." },
    ],
    source: "leicester_removals",
  },
  {
    slug: "edinburgh-removals",
    city: "Edinburgh",
    headline: "Edinb<span class=\"font-display italic font-normal\">u</span>rgh rem<span class=\"font-display italic font-normal\">o</span>v<span class=\"font-display italic font-normal\">a</span>ls.<br />Fixed. Fuss-free.",
    sub: "Tell us about your Edinburgh removal. Verified driver matched by our team. Fixed price from the first call.",
    stats: [
      { stat: "4.9★", label: "Verified reviews" },
      { stat: "< 15m", label: "Response time" },
      { stat: "Fixed", label: "Price. Always." },
      { stat: "EH1–EH55", label: "All postcodes" },
    ],
    steps: STEPS,
    testimonials: [
      { initials: "CH", name: "Callum H.", location: "New Town → Morningside", quote: "Georgian tenement, second floor, no lift. Driver came equipped and handled it perfectly. Fixed price paid exactly as confirmed." },
      { initials: "FM", name: "Fiona M.", location: "Leith → Portobello", quote: "Posted Saturday morning, confirmed Saturday morning, moved Saturday afternoon. Couldn't be simpler." },
      { initials: "GR", name: "Graeme R.", location: "Bruntsfield → Corstorphine", quote: "Fixed price. Professional team. Done by lunchtime. Edinburgh removals rarely go this smoothly." },
    ],
    faq: [
      { q: "Do you cover all Edinburgh postcodes?", a: "We cover all EH postcodes from the Old Town to Livingston and beyond. Seven days a week, 7am to 10pm." },
      { q: "Can you handle Edinburgh tenement flats?", a: "Tenement stairs are something we deal with every day. High floors and narrow access at no extra charge." },
      { q: "Is the price fixed?", a: "Completely fixed. The price confirmed on the call is what you pay. No additions without your approval." },
      { q: "Can you move same-day in Edinburgh?", a: "Same-day is available most days. Post before 10am for the best slots." },
      { q: "Are drivers vetted?", a: "Every driver is background-checked, insured, and rated by real customers before assignment." },
    ],
    source: "edinburgh_removals",
  },
  {
    slug: "cardiff-removals",
    city: "Cardiff",
    headline: "C<span class=\"font-display italic font-normal\">a</span>rdiff rem<span class=\"font-display italic font-normal\">o</span>v<span class=\"font-display italic font-normal\">a</span>ls.<br />Fixed price.",
    sub: "Tell us about your Cardiff removal. Verified driver confirmed by our team. Fixed price guaranteed.",
    stats: [
      { stat: "4.9★", label: "Verified reviews" },
      { stat: "< 15m", label: "Response time" },
      { stat: "Fixed", label: "Price. Always." },
      { stat: "CF1–CF64", label: "All postcodes" },
    ],
    steps: STEPS,
    testimonials: [
      { initials: "BT", name: "Beth T.", location: "Roath → Canton", quote: "Called within a minute. Fixed price confirmed. Driver was professional and early. One of the smoothest moves I've had." },
      { initials: "RO", name: "Rhys O.", location: "Cathays → Pontcanna", quote: "Student move from uni accommodation. No van hire, no faff. Fixed price, done in a morning." },
      { initials: "NP", name: "Nia P.", location: "Splott → Llandaff", quote: "Fixed price is what made me choose them. No vague estimate — a number, and that number was what I paid. Brilliant." },
    ],
    faq: [
      { q: "Do you cover all Cardiff postcodes?", a: "We cover all CF postcodes including Penarth, Barry, and surrounding South Wales areas. Seven days a week, 7am to 10pm." },
      { q: "Is the price fixed?", a: "Always fixed. Confirmed on the call before anything moves. Nothing added on the day." },
      { q: "Can you do student moves in Cardiff?", a: "Cardiff University and Cardiff Met students, end of term, accommodation moves. Fixed price, no van hire." },
      { q: "How quickly do you respond?", a: "Within 15 minutes of posting. Driver and price confirmed before we hang up." },
      { q: "Are drivers verified?", a: "Every driver is background-checked, insured, and rated by real customers before being assigned." },
    ],
    source: "cardiff_removals",
  },
  {
    slug: "newcastle-removals",
    city: "Newcastle",
    headline: "Newc<span class=\"font-display italic font-normal\">a</span>stle rem<span class=\"font-display italic font-normal\">o</span>v<span class=\"font-display italic font-normal\">a</span>ls.<br />Pr<span class=\"font-display italic font-normal\">o</span>per j<span class=\"font-display italic font-normal\">o</span>b.",
    sub: "Tell us about your Newcastle removal. Verified driver. Fixed price. Done right.",
    stats: [
      { stat: "4.9★", label: "Verified reviews" },
      { stat: "< 15m", label: "Response time" },
      { stat: "Fixed", label: "Price. Always." },
      { stat: "NE1–NE46", label: "All postcodes" },
    ],
    steps: STEPS,
    testimonials: [
      { initials: "DB", name: "Dan B.", location: "Jesmond → Gosforth", quote: "Straightforward from start to finish. Fixed price on the call, driver on time, everything delivered without a scratch." },
      { initials: "KF", name: "Kelly F.", location: "Byker → Heaton", quote: "Same-day move sorted by midday. Not a single issue. These guys are as good as it gets." },
      { initials: "SS", name: "Sam S.", location: "Gateshead → Quayside", quote: "Student move, lots of stuff, tight budget. Fixed price meant I knew exactly what I was spending. Worth every penny." },
    ],
    faq: [
      { q: "Do you cover all Newcastle postcodes?", a: "We cover all NE postcodes including Gateshead, Sunderland, and the wider Tyne & Wear area. Seven days a week, 7am to 10pm." },
      { q: "Is the price fixed?", a: "Completely fixed. Confirmed before anything moves. Nothing added on the day without your approval." },
      { q: "Can you do student moves in Newcastle?", a: "Newcastle University and Northumbria students, end of term moves. Fixed price, no van hire." },
      { q: "How fast is the response?", a: "Within 15 minutes of posting. Driver matched and price locked before we hang up." },
      { q: "Are drivers verified?", a: "Every driver is background-checked, insured, and rated by real customers." },
    ],
    source: "newcastle_removals",
  },
  {
    slug: "reading-removals",
    city: "Reading",
    headline: "Re<span class=\"font-display italic font-normal\">a</span>ding rem<span class=\"font-display italic font-normal\">o</span>v<span class=\"font-display italic font-normal\">a</span>ls.<br />Fixed price.",
    sub: "Tell us about your Reading removal. Verified driver confirmed by our team. No surprises.",
    stats: [
      { stat: "4.9★", label: "Verified reviews" },
      { stat: "< 15m", label: "Response time" },
      { stat: "Fixed", label: "Price. Always." },
      { stat: "RG1–RG31", label: "All postcodes" },
    ],
    steps: STEPS,
    testimonials: [
      { initials: "AL", name: "Amy L.", location: "Caversham → Tilehurst", quote: "Fixed price confirmed on the call. Same number paid at the end. Driver was professional and friendly throughout." },
      { initials: "MT", name: "Mark T.", location: "Earley → Woodley", quote: "3-bed house move done in half a day. Two vans, efficient team. Not one scratch. Exactly what you want." },
      { initials: "EP", name: "Emma P.", location: "Reading → Windsor", quote: "Short move but lots of furniture. Fixed price, no fuss, everything placed exactly where asked. Highly recommend." },
    ],
    faq: [
      { q: "Do you cover all Reading postcodes?", a: "We cover all RG postcodes including Bracknell, Wokingham, and surrounding Berkshire areas. Seven days a week, 7am to 10pm." },
      { q: "Is the price fixed?", a: "Completely fixed. Confirmed before anything moves. Nothing added on the day." },
      { q: "How quickly do you respond?", a: "Within 15 minutes of posting. Driver and price confirmed before we hang up." },
      { q: "Can I book same-day in Reading?", a: "Same-day is available most days. Post before 10am for the best slots." },
      { q: "Are drivers verified?", a: "Every driver is background-checked, insured, and rated by real customers before assignment." },
    ],
    source: "reading_removals",
  },
  {
    slug: "oxford-removals",
    city: "Oxford",
    headline: "<span class=\"font-display italic font-normal\">O</span>xf<span class=\"font-display italic font-normal\">o</span>rd rem<span class=\"font-display italic font-normal\">o</span>v<span class=\"font-display italic font-normal\">a</span>ls.<br />Fixed price.",
    sub: "Tell us about your Oxford removal. Verified driver confirmed before you hang up.",
    stats: [
      { stat: "4.9★", label: "Verified reviews" },
      { stat: "< 15m", label: "Response time" },
      { stat: "Fixed", label: "Price. Always." },
      { stat: "OX1–OX44", label: "All postcodes" },
    ],
    steps: STEPS,
    testimonials: [
      { initials: "HG", name: "Hannah G.", location: "Cowley → Summertown", quote: "Oxford parking restrictions and narrow streets — driver navigated it all without a word of complaint. Fixed price paid exactly as agreed." },
      { initials: "FS", name: "Felix S.", location: "Jericho → Headington", quote: "End of term Oxford move. Big room in halls, lots of books. Fixed price, done in an afternoon. Perfect." },
      { initials: "YA", name: "Yasmin A.", location: "Rose Hill → Botley", quote: "Posted Sunday, driver confirmed Sunday, moved Monday. That kind of turnaround is unheard of for Oxford." },
    ],
    faq: [
      { q: "Do you cover all Oxford postcodes?", a: "We cover all OX postcodes including Abingdon, Witney, and surrounding areas. Seven days a week, 7am to 10pm." },
      { q: "Can you handle Oxford parking and access challenges?", a: "Permit zones, narrow roads, and college restrictions are all assessed upfront and factored into your fixed price." },
      { q: "Is the price fixed?", a: "Completely fixed. Confirmed on the call before anything moves. Nothing added on the day." },
      { q: "Can you do student moves in Oxford?", a: "Oxford and Oxford Brookes student moves, end of term, halls to house. Fixed price, no van hire." },
      { q: "Are drivers vetted?", a: "Every driver is background-checked, insured, and rated by real customers before being assigned." },
    ],
    source: "oxford_removals",
  },
  {
    slug: "cambridge-removals",
    city: "Cambridge",
    headline: "C<span class=\"font-display italic font-normal\">a</span>mbr<span class=\"font-display italic font-normal\">i</span>dge rem<span class=\"font-display italic font-normal\">o</span>v<span class=\"font-display italic font-normal\">a</span>ls.<br />Fixed price.",
    sub: "Tell us about your Cambridge removal. Verified driver confirmed before you hang up.",
    stats: [
      { stat: "4.9★", label: "Verified reviews" },
      { stat: "< 15m", label: "Response time" },
      { stat: "Fixed", label: "Price. Always." },
      { stat: "CB1–CB25", label: "All postcodes" },
    ],
    steps: STEPS,
    testimonials: [
      { initials: "JL", name: "James L.", location: "Hills Road → Chesterton", quote: "Student move at the end of Michaelmas. Posted on a Friday, confirmed on Friday, moved Saturday. Exceptional turnaround." },
      { initials: "KN", name: "Kristina N.", location: "City Centre → Cherry Hinton", quote: "Bike and furniture move across Cambridge. Fixed price, no extras, driver was careful with everything. Perfect." },
      { initials: "OA", name: "Oliver A.", location: "Arbury → Trumpington", quote: "3-bed house. Two careful movers, two hours, done by noon. The fixed price is what makes this service genuinely different." },
    ],
    faq: [
      { q: "Do you cover all Cambridge postcodes?", a: "We cover all CB postcodes including Ely, St Ives, and surrounding Cambridgeshire areas. Seven days a week, 7am to 10pm." },
      { q: "Can you do student moves in Cambridge?", a: "Cambridge University and Anglia Ruskin student moves, end of term, any accommodation. Fixed price, no van hire." },
      { q: "Is the price fixed?", a: "Completely fixed. Confirmed before anything moves. Nothing added on move day." },
      { q: "How quickly do you respond?", a: "Within 15 minutes of posting. Driver and price confirmed before we hang up." },
      { q: "Are drivers verified?", a: "Every driver is background-checked, insured, and rated by real customers." },
    ],
    source: "cambridge_removals",
  },
  {
    slug: "southampton-removals",
    city: "Southampton",
    headline: "S<span class=\"font-display italic font-normal\">o</span>uth<span class=\"font-display italic font-normal\">a</span>mpt<span class=\"font-display italic font-normal\">o</span>n rem<span class=\"font-display italic font-normal\">o</span>v<span class=\"font-display italic font-normal\">a</span>ls.<br />Fixed price.",
    sub: "Tell us about your Southampton removal. Verified driver confirmed. Fixed price guaranteed.",
    stats: [
      { stat: "4.9★", label: "Verified reviews" },
      { stat: "< 15m", label: "Response time" },
      { stat: "Fixed", label: "Price. Always." },
      { stat: "SO1–SO53", label: "All postcodes" },
    ],
    steps: STEPS,
    testimonials: [
      { initials: "GH", name: "Georgia H.", location: "Portswood → Bitterne", quote: "Southampton student move sorted in one afternoon. Fixed price, no van, no stress. Incredible service." },
      { initials: "DK", name: "Dom K.", location: "Ocean Village → Shirley", quote: "Port-area flat with awkward access. Driver came prepared, handled it smoothly. Fixed price paid exactly as quoted." },
      { initials: "NW", name: "Natasha W.", location: "Shirley → Hedge End", quote: "Posted the job and called back in under a minute. That level of response time had me confident before the move even started." },
    ],
    faq: [
      { q: "Do you cover all Southampton postcodes?", a: "We cover all SO postcodes including Portsmouth, Eastleigh, and surrounding Hampshire areas. Seven days a week, 7am to 10pm." },
      { q: "Is the price fixed?", a: "Completely fixed. Confirmed on the call before anything moves. Nothing added on move day." },
      { q: "Can you do student moves in Southampton?", a: "University of Southampton and Solent students, end of term moves. Fixed price, no van hire." },
      { q: "How quickly do you respond?", a: "Within 15 minutes of posting. Driver matched and price locked before we hang up." },
      { q: "Are drivers verified?", a: "Every driver is background-checked, insured, and rated by real customers before assignment." },
    ],
    source: "southampton_removals",
  },
  {
    slug: "brighton-removals",
    city: "Brighton",
    headline: "Brght<span class=\"font-display italic font-normal\">o</span>n rem<span class=\"font-display italic font-normal\">o</span>v<span class=\"font-display italic font-normal\">a</span>ls.<br />Fixed price.",
    sub: "Tell us about your Brighton removal. Verified driver. Fixed price. Done properly.",
    stats: [
      { stat: "4.9★", label: "Verified reviews" },
      { stat: "< 15m", label: "Response time" },
      { stat: "Fixed", label: "Price. Always." },
      { stat: "BN1–BN45", label: "All postcodes" },
    ],
    steps: STEPS,
    testimonials: [
      { initials: "TC", name: "Tom C.", location: "Hove → Kemp Town", quote: "Brighton streets are chaos. Driver navigated it without complaint and parked exactly where needed. Fixed price. Job done." },
      { initials: "IM", name: "Isla M.", location: "North Laine → Preston Park", quote: "First-floor flat, no lift, lots of art. Everything wrapped, moved, placed. Not one mark anywhere." },
      { initials: "PF", name: "Pete F.", location: "Hanover → Fiveways", quote: "Posted on a Saturday, confirmed on a Saturday, moved Sunday morning. That's the kind of service that gets referrals." },
    ],
    faq: [
      { q: "Do you cover all Brighton postcodes?", a: "We cover all BN postcodes including Hove, Worthing, and the Sussex coast. Seven days a week, 7am to 10pm." },
      { q: "Can you handle Brighton's narrow streets?", a: "Brighton's parking and access challenges are assessed upfront and included in your fixed price. No surprises." },
      { q: "Is the price fixed?", a: "Completely fixed. Confirmed before anything moves. Nothing added on the day." },
      { q: "How quickly do you respond?", a: "Within 15 minutes of posting. Driver and price confirmed before we hang up." },
      { q: "Are drivers verified?", a: "Every driver is background-checked, insured, and rated by real customers." },
    ],
    source: "brighton_removals",
  },
  {
    slug: "derby-removals",
    city: "Derby",
    headline: "Derby rem<span class=\"font-display italic font-normal\">o</span>v<span class=\"font-display italic font-normal\">a</span>ls.<br />Fixed price.",
    sub: "Tell us about your Derby removal. Verified driver matched and confirmed by our team.",
    stats: [
      { stat: "4.9★", label: "Verified reviews" },
      { stat: "< 15m", label: "Response time" },
      { stat: "Fixed", label: "Price. Always." },
      { stat: "DE1–DE75", label: "All postcodes" },
    ],
    steps: STEPS,
    testimonials: [
      { initials: "WH", name: "Will H.", location: "Allestree → Spondon", quote: "Responsive, professional, and fixed price from the start. Exactly what every removal company should be." },
      { initials: "SN", name: "Sophie N.", location: "City Centre → Mickleover", quote: "Same-day removal sorted by midday. Driver was excellent, everything arrived safely. No complaints whatsoever." },
      { initials: "BM", name: "Ben M.", location: "Chaddesden → Oakwood", quote: "3-bed house, two vans, done by 3pm. Fixed price paid, no extras. Outstanding service." },
    ],
    faq: [
      { q: "Do you cover all Derby postcodes?", a: "We cover all DE postcodes including Burton upon Trent, Long Eaton, and surrounding areas. Seven days a week, 7am to 10pm." },
      { q: "Is the price fixed?", a: "Completely fixed. Confirmed on the call before anything moves. Nothing added on move day." },
      { q: "How quickly do you respond?", a: "Within 15 minutes of posting. Driver matched and price locked before we hang up." },
      { q: "Can I book same-day in Derby?", a: "Same-day is available most days. Post before 10am for the best slots." },
      { q: "Are drivers verified?", a: "Every driver is background-checked, insured, and rated by real customers before assignment." },
    ],
    source: "derby_removals",
  },
  {
    slug: "wolverhampton-removals",
    city: "Wolverhampton",
    headline: "W<span class=\"font-display italic font-normal\">o</span>lverh<span class=\"font-display italic font-normal\">a</span>mpt<span class=\"font-display italic font-normal\">o</span>n rem<span class=\"font-display italic font-normal\">o</span>v<span class=\"font-display italic font-normal\">a</span>ls.<br />Fixed.",
    sub: "Tell us about your Wolverhampton removal. Verified driver. Fixed price guaranteed.",
    stats: [
      { stat: "4.9★", label: "Verified reviews" },
      { stat: "< 15m", label: "Response time" },
      { stat: "Fixed", label: "Price. Always." },
      { stat: "WV1–WV16", label: "All postcodes" },
    ],
    steps: STEPS,
    testimonials: [
      { initials: "JP", name: "James P.", location: "Penn → Tettenhall", quote: "Posted at 8am. Called back at 8:01. Driver confirmed and price locked before breakfast. That's a proper service." },
      { initials: "VK", name: "Vikram K.", location: "Wednesfield → Bilston", quote: "Fixed price is the only honest way to quote a removal. These guys do it right. Smooth move, no drama." },
      { initials: "CH", name: "Claire H.", location: "Whitmore Reans → Finchfield", quote: "2-bed flat, professional team, done in three hours. Worth every penny and then some." },
    ],
    faq: [
      { q: "Do you cover all Wolverhampton postcodes?", a: "We cover all WV postcodes including Walsall, Dudley, and surrounding West Midlands areas. Seven days a week, 7am to 10pm." },
      { q: "Is the price fixed?", a: "Completely fixed. Confirmed on the call before anything moves. Nothing added on move day." },
      { q: "How quickly do you respond?", a: "Within 15 minutes of posting. Driver and price confirmed before we hang up." },
      { q: "Can I book same-day?", a: "Same-day is available most days. Post before 10am for the best slots." },
      { q: "Are drivers background-checked?", a: "Every driver is verified, insured, and rated by real customers before being assigned." },
    ],
    source: "wolverhampton_removals",
  },
  {
    slug: "norwich-removals",
    city: "Norwich",
    headline: "N<span class=\"font-display italic font-normal\">o</span>rwich rem<span class=\"font-display italic font-normal\">o</span>v<span class=\"font-display italic font-normal\">a</span>ls.<br />Fixed price.",
    sub: "Tell us about your Norwich removal. Verified driver matched by our team. Fixed price guaranteed.",
    stats: [
      { stat: "4.9★", label: "Verified reviews" },
      { stat: "< 15m", label: "Response time" },
      { stat: "Fixed", label: "Price. Always." },
      { stat: "NR1–NR35", label: "All postcodes" },
    ],
    steps: STEPS,
    testimonials: [
      { initials: "EH", name: "Emily H.", location: "Golden Triangle → Thorpe St Andrew", quote: "Fixed price quoted. Fixed price paid. Simple, honest, and professional. Exactly what a removal service should be." },
      { initials: "CP", name: "Charlie P.", location: "City Centre → Eaton", quote: "Student move from UEA halls. No van, no faff, no friends guilt-tripped. Fixed price, done in a morning." },
      { initials: "MN", name: "Mark N.", location: "Aylsham → Norwich", quote: "Cross-county move, lots of furniture, awkward staircase. Driver and assistant handled everything without complaint." },
    ],
    faq: [
      { q: "Do you cover all Norwich postcodes?", a: "We cover all NR postcodes including Great Yarmouth, Dereham, and surrounding Norfolk areas. Seven days a week, 7am to 10pm." },
      { q: "Is the price fixed?", a: "Completely fixed. Confirmed before anything moves. Nothing added on move day without your approval." },
      { q: "Can you do student moves in Norwich?", a: "UEA student moves, end of term, halls to flat. Fixed price, no van hire." },
      { q: "How quickly do you respond?", a: "Within 15 minutes of posting. Driver matched and price locked before we hang up." },
      { q: "Are drivers verified?", a: "Every driver is background-checked, insured, and rated by real customers." },
    ],
    source: "norwich_removals",
  },
  {
    slug: "south-london-removals",
    city: "South London",
    headline: "S<span class=\"font-display italic font-normal\">o</span>uth L<span class=\"font-display italic font-normal\">o</span>nd<span class=\"font-display italic font-normal\">o</span>n rem<span class=\"font-display italic font-normal\">o</span>v<span class=\"font-display italic font-normal\">a</span>ls.<br />Fixed price.",
    sub: "Tell us about your South London removal. Verified local driver. Fixed price confirmed on the call.",
    stats: [
      { stat: "4.9★", label: "Verified reviews" },
      { stat: "< 15m", label: "Response time" },
      { stat: "Fixed", label: "Price. Always." },
      { stat: "SE & SW", label: "All postcodes" },
    ],
    steps: STEPS,
    testimonials: [
      { initials: "LK", name: "Lara K.", location: "Brixton → Herne Hill", quote: "Posted and called back before I'd finished my coffee. SE London driver confirmed, fixed price locked. Flawless." },
      { initials: "QM", name: "Quinn M.", location: "Clapham → Balham", quote: "SW London parking restrictions, narrow Victorian street. Driver had a plan before arriving. Fixed price. Perfect." },
      { initials: "BD", name: "Ben D.", location: "Peckham → Crystal Palace", quote: "SE12 to SE19 — quick move but lots of furniture. Done in two hours. Fixed price paid exactly as quoted." },
    ],
    faq: [
      { q: "Which South London postcodes do you cover?", a: "All SE and SW postcodes — Brixton, Clapham, Peckham, Lewisham, Croydon, Wimbledon, Tooting and beyond. 7 days a week." },
      { q: "Do you handle ULEZ and congestion zones?", a: "All South London ULEZ charges and parking costs are included in your fixed price. Nothing added on the day." },
      { q: "Is the price fixed?", a: "Completely fixed. Confirmed on the call before anything moves." },
      { q: "How quickly do you respond?", a: "Within 15 minutes of posting. Driver matched and price locked before we hang up." },
      { q: "Can I book same-day in South London?", a: "Same-day is a speciality. Post before 10am for same-day availability." },
    ],
    source: "south_london_removals",
  },
  {
    slug: "east-london-removals",
    city: "East London",
    headline: "E<span class=\"font-display italic font-normal\">a</span>st L<span class=\"font-display italic font-normal\">o</span>nd<span class=\"font-display italic font-normal\">o</span>n rem<span class=\"font-display italic font-normal\">o</span>v<span class=\"font-display italic font-normal\">a</span>ls.<br />Fixed price.",
    sub: "Tell us about your East London removal. Verified local driver. Fixed price confirmed before anything moves.",
    stats: [
      { stat: "4.9★", label: "Verified reviews" },
      { stat: "< 15m", label: "Response time" },
      { stat: "Fixed", label: "Price. Always." },
      { stat: "E1–E20", label: "All postcodes" },
    ],
    steps: STEPS,
    testimonials: [
      { initials: "MH", name: "Maya H.", location: "Hackney → Stratford", quote: "E9 to E15 in two hours. Fixed price, professional team, everything placed exactly where I asked. Outstanding." },
      { initials: "JB", name: "Jake B.", location: "Shoreditch → Walthamstow", quote: "Bethnal Green flat, third floor. Driver assessed the access and had a plan. Fixed price. Smooth from start to finish." },
      { initials: "AC", name: "Amara C.", location: "Bow → Canary Wharf", quote: "Same-day move confirmed at 9am, done by 2pm. East London removals don't get easier than this." },
    ],
    faq: [
      { q: "Which East London postcodes do you cover?", a: "All E postcodes — Hackney, Shoreditch, Stratford, Walthamstow, Bethnal Green, Bow, and beyond. 7 days a week." },
      { q: "Do you handle ULEZ and congestion charges?", a: "All charges are factored into your fixed price upfront. Nothing added on move day." },
      { q: "Is the price fixed?", a: "Completely fixed. Confirmed on the call before anything moves." },
      { q: "How quickly do you respond?", a: "Within 15 minutes of posting. Driver matched and price locked before we hang up." },
      { q: "Can I book same-day in East London?", a: "Same-day is a speciality. Post before 10am for same-day availability." },
    ],
    source: "east_london_removals",
  },
  {
    slug: "manchester-removals",
    city: "Manchester",
    headline: "M<span class=\"font-display italic font-normal\">a</span>nchester rem<span class=\"font-display italic font-normal\">o</span>v<span class=\"font-display italic font-normal\">a</span>ls.<br />Fixed price.",
    sub: "Tell us about your Manchester removal. Verified driver matched by our team. Fixed price guaranteed.",
    stats: [
      { stat: "4.9★", label: "Verified reviews" },
      { stat: "< 15m", label: "Response time" },
      { stat: "Fixed", label: "Price. Always." },
      { stat: "M1–M90", label: "All postcodes" },
    ],
    steps: STEPS,
    testimonials: [
      { initials: "KM", name: "Kate M.", location: "Northern Quarter → Didsbury", quote: "M1 to M20 — across Manchester in two hours. Fixed price confirmed before they left the depot. Outstanding." },
      { initials: "TD", name: "Tom D.", location: "Salford → Chorlton", quote: "Student move from Salford Uni. Fixed price, no van hire nightmare, driver arrived on time. Exactly what you'd want." },
      { initials: "RA", name: "Riya A.", location: "Ancoats → Hulme", quote: "Posted Sunday morning. Confirmed Sunday morning. Moved Sunday afternoon. Exceptional turnaround." },
    ],
    faq: [
      { q: "Do you cover all Manchester postcodes?", a: "We cover all M postcodes including Salford, Stockport, Oldham, and Greater Manchester. Seven days a week, 7am to 10pm." },
      { q: "Is the price fixed?", a: "Completely fixed. Confirmed before anything moves. Nothing added on the day without your approval." },
      { q: "Can you do student moves in Manchester?", a: "Manchester University and Manchester Met student moves. Fixed price, end of term, no van hire." },
      { q: "How quickly do you respond?", a: "Within 15 minutes of posting. Driver matched and price locked before we hang up." },
      { q: "Are drivers verified?", a: "Every driver is background-checked, insured, and rated by real customers before assignment." },
    ],
    source: "manchester_removals",
  },
];

export function getCityBySlug(slug: string) {
  return PROGRAMMATIC_CITIES.find(c => c.slug === slug) ?? null;
}
