export const DELIVERY_TYPES = [
  "Legal Documents",
  "Medical Supplies",
  "Medical Specimens",
  "Vehicle Parts",
  "Engineering Parts",
  "Construction Materials",
  "Keys & Access Devices",
  "IT Equipment",
  "Retail Stock",
  "Event Equipment",
  "Printed Materials",
  "Contracts",
  "Tender Documents",
  "Electronics",
  "Sensitive Documents",
  "Replacement Parts",
  "Promotional Materials",
  "Samples",
  "High Value Items",
  "Confidential Packages",
  "Other",
];
